[package]
name = "sphinx-passwords"
version = "0.1.0"
authors = ["Jos√© Ney Guerrero <joseneyguerrero@gmail.com>"]

[lib]
name = "random_things"
path = "src/lib.rs"

[dependencies]
argparse = "0.2.1"
rand = "0.3.14"
ansi_term = "0.7"
